version: '3.8'

services:
  server:
    build: ./server
    container_name: shopsmart-server
    ports:
      - "5001:5000"
    restart: always

  client:
    build: ./client
    container_name: shopsmart-client
    ports:
      - "3000:80" # Mapping to port 80 as defined in the updated Nginx Dockerfile
    depends_on:
      - server
    restart: always